### ISSUE TITLE
duplicate symbols for architecture arm64

### ISSUE THREAD

**Issue by amohiy** [kaltura/playkit-ios-googlecast#5]
Hello,
i am using PlayKitGoogleCast 1.2.0 to play videos on google chrome cast, And i am also using Firebase/firstore pod. and when i am trying to build the app i always get this error: [ duplicate symbols for architecture arm64 ] [ linker command failed with exit code 1 ]

i am using kaltura player V3, Xcode 10.2,  what should i do.

Thanks in advance.

**Comment by kaltura-hooks** [comment]
Hi @amohiy,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by x-NR-x** [comment]
Hi @amohiy,

Thank you for contacting us.
Can you please check and attach the error log for the duplicates, so that I can see who they are and try to assist you.

Thanks,
Nilit Danan

**Comment by ElizaSapir** [comment]
@x-NR-x hey,

It looks like you have duplicate symbols with the following libraries: Firebase - GoogleCast. 

Firebase is owned by Google so I guess thats why they use the same symbols of some classes that already exist in GoogleCast.

I'd try updating both of those frameworks/pods, and hopefully newer versions fixed it. 

Let me know if I can help :)

**Comment by amohiy** [comment]
hey @x-NR-x and @ElizaSapir ,
Thanks both for your help. What @ElizaSapir said is correct. The conflict happens between   Firebase - GoogleCast frameworks. I appreciate that you are going to update the frameworks with the fix. Should i do anything from my side? And can you let me know when the Frameworks will be ready to be used, Please.

Thanks in advance.

**Comment by x-NR-x** [comment]
Hi @amohiy,

In order to assist you, I would still be happy to see your error message log.
As well, please send me your 'pod' file and 'podfile.lock' file.

From what I saw, between FirebaseFirestore pod latest version (1.5.1) and google-cast-sdk v4.4.4, they both have dependencies to Protobuf, and probably there is the issue.
Our latest PlayKitGoogleCast v1.3.0, is using google-cast-sdk v4.4.4.

I created a sample which has PlayKitGoogleCast 1.3.0 and FirebaseFirestore 1.5.1, and the build succeeds with no errors, therefore, I can't see the issue you are encountering. 

Please try to update the pods you are using, FirebaseFirestore and PlayKitGoogleCast, if they are not the latest.

Please update me.

Thanks,
Nilit Danan

**Comment by x-NR-x** [comment]
Hi @amohiy,

Do you still have an issue with this?

Thanks,
Nilit Danan
